In [1]:
# # Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# # to print the data types of both the variables.
# Yes, there is a difference in the data types of the variables list_ and array_list. list_ is a Python list object, whereas array_list is a NumPy array object.
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print the data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
# #Q3 Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

# Print data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# # (ii) size
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# Find the shape of num_array
array_shape = num_array.shape

# Find the size of num_array
array_size = num_array.size

# Print the shape and size
print("Shape of num_array:", array_shape)
print("Size of num_array:", array_size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [6]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
import numpy as np

# Create a 3x3 matrix of zeros
zero_array = np.zeros((3, 3))

# Print the zero_array
print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the identity matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
